DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes
# MOUSEKEY_ENABLE = yes
# TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

SRC += repeat.c

LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no